--require('core/plugin_config/lualine')
require('core/plugin_config/nvim-tree')
require('core/plugin_config/telescope')
require('core/plugin_config/treesitter')
require('core/plugin_config/lsp_config')
require('core/plugin_config/completions')
require('core/plugin_config/orgmode')
require('core/plugin_config/better-escape')

-- Colorschemes (choose one)
--require('core/plugin_config/gruvbox')
--require('core/plugin_config/rose-pine')
--require('core/plugin_config/everblush')
require('core/plugin_config/mellifluous')
