local glo = vim.g
local opt = vim.opt

opt.laststatus = 0
opt.showtabline = 0
opt.showmode = true
opt.expandtab = true
opt.tabstop = 8
opt.shiftwidth = 4
opt.softtabstop = 4
opt.mouse = "a"
opt.shortmess = "a"
opt.timeoutlen = 200
opt.number = true
opt.relativenumber = true
opt.clipboard = "unnamedplus"
opt.wrap = true
opt.smarttab = true
opt.autoindent = true
opt.backup = false
opt.writebackup = false
opt.undofile = false
opt.swapfile = false
opt.scrolloff = 7
opt.hlsearch = true
opt.lazyredraw = true
opt.ruler = true
opt.path = "**"
opt.wildmenu = true
opt.wildignore = "*.docx,*.jpg,*.png,*.gif,*.pdf,*.exe,*.o,*.mp3,*.mp4,*.mov,*.mkv,*.ogg,*.dat"
opt.encoding = "UTF-8"
opt.pumheight = 10

glo.mapleader = " "
