#!/bin/sh

result="<result>"
while true; do
    expr="$(echo "$result" | dmenu -p "Enter expression:")"
    case $expr in
        ""|"exit")
            exit
            ;;
        *)
            result="$(echo "$expr" | bc)"
            ;;
    esac
done
