#!/bin/sh

mpc status | grep "playing" 2> /dev/null
if [ $? -eq 0 ]; then playing=">"; else playing="-"; fi

status="[$playing] $(mpc current -f "%title%")"

choice=$(echo "play/pause\njump\nartist\nalbum\ntrack\nload\nclear\ntoggle" | dmenu -p "$status")

dir="${HOME}/.config/dmenu/scripts/"

case $choice in
    play/pause)
        mpc toggle
        ;;
    jump)
        $dir/dm-mpd -j
        ;;
    artist)
        $dir/dm-mpd -a
        ;;
    album)
        $dir/dm-mpd -l
        ;;
    track)
        $dir/dm-mpd -t
        ;;
    load)
        $dir/dm-mpd -p
        ;;
    clear)
        mpc clear
        ;;
    toggle)
        mpc status | grep "random: on" 2> /dev/null
        if [ $? -eq 0 ]; then random="?"; else random="-"; fi
        mpc status | grep "consume: on" 2> /dev/null
        if [ $? -eq 0 ]; then consume="X"; else consume="-"; fi
        mpc status | grep "repeat: on" 2> /dev/null
        if [ $? -eq 0 ]; then repeat="@"; else repeat="-"; fi

        status="[$random$consume$repeat]"
        option=$(echo "random\nconsume\nrepeat" | dmenu -p $status)

        case $option in
            random)
                mpc random
                ;;
            consume)
                mpc consume
                ;;
            repeat)
                mpc repeat
                ;;
        esac
        ;;
esac
