#!/usr/bin/env bash

#  ██                     ██                ██    ██           ████   ██
# ░██                    ░██               ░██   ░██          ░██░   ░██
# ░██       █████  ██████░██       ██████ ██████ ░██ ██   ██ ██████ ██████
# ░██████  ██░░░██░░██░░█░██████  ██░░░░ ░░░██░  ░██░██  ░██░░░██░ ░░░██░
# ░██░░░██░███████ ░██ ░ ░██░░░██░░█████   ░██   ░██░██  ░██  ░██    ░██
# ░██  ░██░██░░░░  ░██   ░██  ░██ ░░░░░██  ░██   ░██░██  ░██  ░██    ░██
# ░██  ░██░░██████░███   ░██████  ██████   ░░██  ███░░██████  ░██    ░░██
# ░░   ░░  ░░░░░░ ░░░    ░░░░░   ░░░░░░     ░░  ░░░  ░░░░░░   ░░      ░░

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc set focus_follows_mouse 1
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc attr theme.title_font 'mononoki NF:pixelsize=12'
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.inner_width 1
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.title_height 0
hc attr theme.padding_top 0  # space below the title's baseline (i.e. text depth)
hc attr theme.active.outer_width 1
hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set tree_style '╾│ ├└╼─┐'

source "$HOME/.config/herbstluftwm/keybinds"
source "$HOME/.config/herbstluftwm/colors"

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH|POPUP_MENU)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'.*-prompter|.*\.exe|scratchpad|[Dd]ragon|[Ss]xiv|[Ss]team|[Mm]pv' floating=on
hc rule windowrole='GtkFileChooserDialog' floating=on

# unlock, just to be sure
hc unlock

# monitors
#hc set_monitors 1280x1024+0+0 1280x1024+1280+0
hc detect_monitors

# find the panel
panel=~/.config/polybar/launch.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done

#actually autostart applications
if hc silent new_attr bool my_not_first_autostart ; then
    setxkbmap es &
    xset r rate 300 35 &
    nitrogen --restore &
    picom &
    mpd &
    redshift -l 41.39:2.16 -m randr -t 5500:5000 &
    /usr/bin/nvidia-settings -l &
    emacs --daemon &
fi
