#!/usr/bin/env bash

#accent='#D19A66'
accent='#346475'
#foreground='#D19A66'
foreground='#D1D1D1'
background='#151515'

xsetroot -solid $accent

hc set frame_border_active_color '#222222'
hc set frame_border_normal_color $background
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'

hc attr theme.title_color '#ffffff'
hc attr theme.background_color $background
hc attr theme.inner_color black
hc attr theme.floating.outer_color black

hc attr theme.normal.color $background
hc attr theme.normal.inner_color $background
hc attr theme.normal.title_color '#898989'

hc attr theme.active.color $accent
hc attr theme.active.inner_color $accent

hc attr theme.urgent.color '#7811A1dd'
hc attr theme.urgent.inner_color '#1E4D3D'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
