#!/usr/bin/env bash

hc keyunbind --all

terminal="${TERMINAL:-xterm}"
browser="${BROWSER:-firefox}"
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )
resizestep=0.02
Mod=Mod4
AMod=Mod1

# Programas
hc keybind $Mod-Escape          spawn slock
hc keybind $Mod-Return          spawn $terminal
hc keybind $Mod-d               spawn dmenu_run -h 12 -c -g 3 -l 10
hc keybind $Mod-b               spawn $browser
hc keybind $Mod-a               spawn pcmanfm
hc keybind $Mod-e               spawn emacsclient -c -a 'emacs'

# Scripts
hc keybind $Mod-m               spawn $SCRIPTSDIR/music.sh
hc keybind $Mod-p               spawn $SCRIPTSDIR/password.sh
hc keybind $Mod-$AMod-o         spawn $SCRIPTSDIR/soundout.sh
hc keybind $Mod-$AMod-k         spawn $SCRIPTSDIR/kill.sh
hc keybind $Mod-$AMod-e         spawn $SCRIPTSDIR/editcfg.sh
hc keybind $Mod-Insert          spawn $SCRIPTSDIR/snippet.sh 1
hc keybind $Mod-$AMod-b         spawn $SCRIPTSDIR/snippet.sh 2
hc keybind $Mod-plus            spawn $SCRIPTSDIR/volume.sh 1
hc keybind $Mod-minus           spawn $SCRIPTSDIR/volume.sh 2
hc keybind $Mod-Print           spawn $SCRIPTSDIR/screenshot.sh 1
hc keybind $Mod-$AMod-Print     spawn $SCRIPTSDIR/screenshot.sh 2
hc keybind $Mod-Shift-Print     spawn $SCRIPTSDIR/screenshot.sh 3
hc keybind $Mod-Control-Print   spawn $SCRIPTSDIR/screenshot.sh 4
hc keybind $Mod-Shift-q         spawn $SCRIPTSDIR/wmquit.sh

# Moverse entre ventanas
hc keybind $Mod-h               focus left
hc keybind $Mod-j               focus down
hc keybind $Mod-k               focus up
hc keybind $Mod-l               focus right
hc keybind $Mod-Left            focus left
hc keybind $Mod-Down            focus down
hc keybind $Mod-Up              focus up
hc keybind $Mod-Right           focus right
hc keybind $Mod-c               cycle
hc keybind $Mod-Tab             cycle_all +1
hc keybind $Mod-Shift-Tab       cycle_all -1
hc keybind $Mod-Delete          cycle_monitor
hc keybind $Mod-i               jumpto urgent

# Cambiar ventanas
hc keybind $Mod-Shift-h         shift left
hc keybind $Mod-Shift-j         shift down
hc keybind $Mod-Shift-k         shift up
hc keybind $Mod-Shift-l         shift right
hc keybind $Mod-Shift-Left      shift left
hc keybind $Mod-Shift-Down      shift down
hc keybind $Mod-Shift-Up        shift up
hc keybind $Mod-Shift-Right     shift right

# Estructura de ventanas
hc keybind $Mod-w               close
hc keybind $Mod-f               fullscreen toggle
# hc keybind $Mod-s               set_attr clients.focus.floating toggle
hc keybind $Mod-t               floating toggle
hc keybind $Mod-Shift-m         set_attr clients.focus.minimized true
hc keybind $Mod-Control-m       jumpto last-minimized

# Crear marcos
hc keybind $Mod-u               split bottom  0.5
hc keybind $Mod-o               split right   0.5
hc keybind $Mod-Control-space   split explode
hc keybind $Mod-q               remove

# Cambiar tamaño de marcos
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# Raton
hc mouseunbind --all
hc mousebind $Mod-Button1       move
hc mousebind $Mod-Button2       zoom
hc mousebind $Mod-Button3       resize

# General
hc keybind $Mod-Shift-r         reload
hc keybind $Mod-F1              spawn $terminal -e less /usr/share/doc/help_hlwm.txt

# Tags
hc keybind $Mod-period          use_index +1 --skip-visible
hc keybind $Mod-comma           use_index -1 --skip-visible

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
 
    # The following cycles through the available layouts within a frame, but skips
    # layouts, if the layout change wouldn't affect the actual window positions.
    # I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
