(setq gc-cons-threshold 10000000)
(setq byte-compile-warnings '(not obsolete))
(setq warning-suppress-log-types '((comp) (bytecomp)))
(setq native-comp-async-report-warnings-errors 'silent)
(setq inhibit-startup-echo-area-message (user-login-name))
(setq frame-resize-pixelwise t)
(tool-bar-mode -1)
(menu-bar-mode -1)
(tooltip-mode -1)
(put 'dired-find-alternate-file 'disabled nil)
(when (cdr command-line-args)
  (setq inhibit-startup-screen t))
(setq default-frame-alist '(;(fullscreen . maximized)
                            (alpha . 100)
                            (vertical-scroll-bars . nil)
                            (horizontal-scroll-bars . nil)
                            (background-color . "#000000")
                            (ns-appearance . dark)
                            (ns-transparent-titlebar . t)
                            (left-fringe . 0)
                            (right-fringe . 0)))
