config.bind('ñ', 'set-cmd-text :')
config.bind('o', 'set-cmd-text -s :open')
config.bind('O', 'set-cmd-text :open {url}')
config.bind('t', 'set-cmd-text -s :open -t')
config.bind('T', 'set-cmd-text :open -t {url}')
config.bind('b', 'set-cmd-text -s :quickmark-load')
config.bind('B', 'set-cmd-text -s :quickmark-load -t')
config.bind('y', 'yank pretty-url')
config.bind('Y', 'yank selection')
config.bind('p', 'open {clipboard}')
config.bind('P', 'open -t {clipboard}')
config.bind('c', 'download-clear;; clear-messages')
config.bind('d', 'tab-close')
config.bind('Q', 'close')
config.bind('<Ctrl-c>', 'mode-leave', 'command')
config.bind('gh', 'home')
config.bind('gc', 'config-edit')
config.bind('xb', 'config-cycle statusbar.show never always')
config.bind('xt', 'config-cycle tabs.show multiple switching')
config.bind('xc', 'history-clear')
config.bind('Ctrl-p', 'tab-pin')
config.bind('<Ctrl-j>', 'tab-move +')
config.bind('<Ctrl-k>', 'tab-move -')
config.bind('<Ctrl-h>', 'tab-prev')
config.bind('<Ctrl-l>', 'tab-next')
config.bind('<Ctrl-i>', 'forward')
config.bind('<Ctrl-o>', 'back')
config.bind('<Ctrl-z>', 'mode-enter passthrough')
config.bind('<ctrl+shift+p>', 'open -p')

config.bind(',m', 'hint links spawn mpv {hint-url}')
config.bind(',M', 'spawn mpv {url}')
config.bind(',t', 'spawn --userscript translate --text')
config.bind(',T', 'spawn --userscript translate')
config.bind(',d', 'download-open')
config.bind('<Ctrl-y>', 'spawn --userscript password_fill')

config.bind('<Ctrl-y>', 'spawn --userscript password_fill', 'insert')
config.bind('<Ctrl-d>', 'mode-leave', 'insert')
config.bind('<Ctrl-h>', 'fake-key <Backspace>', 'insert')
config.bind('<Ctrl-a>', 'fake-key <Home>', 'insert')
config.bind('<Ctrl-e>', 'fake-key <End>', 'insert')
config.bind('<Ctrl-b>', 'fake-key <Delete>', 'insert')
config.bind('<Ctrl-w>', 'fake-key <Ctrl-Backspace>', 'insert')
config.bind('<Ctrl-u>', 'fake-key <Shift-Home><Delete>', 'insert')
config.bind('<Ctrl-k>', 'fake-key <Shift-End><Delete>', 'insert')
